### ISSUE TITLE
Clutterreport: /storage/emulated/0/searchlite/backup (new)

### ISSUE THREAD

**Issue by david082321** [d4rken/sdmaid-public#738] opened 2017-02-11 05:34 UTC
### Target
Target: `/storage/emulated/0/searchlite/backup`
Prefix-free: `searchlite/backup`
Path-prefix: `/storage/emulated/0/`
Type: `DIRECTORY`
Location: `SDCARD`
Current keeper state: `false`
Suggested keeper state: `true`

### Suggested owners
Appname: `搜索 Lite`
Packagename: `com.orekie.search`
Version: `40 fix (65)`

### Current owners
None

### SD Maid
Version: `4.5.9 (40509)`

### Device
Fingerprint: `samsung/a7y17ltezt/a7y17lte:6.0.1/MMB29K/A720FZTU1APL7:user/release-keys`

### Comment
`backups`

**Comment by d4rken** [comment] 2017-02-11 06:01
Duplicate of #737 

SD Maid tracks only top level directories, so if a subfolder should be a keeper, the top folder should be one too.

**Closed by d4rken** 2017-02-11 06:01 UTC
Labels: c: Definitions
