### ISSUE TITLE
constant queued state - Q beta 6

### ISSUE THREAD

**Issue by jancm** [d4rken/sdmaid-public#2867] opened 2019-08-10 14:33 UTC
SDMaid 4.14.32
Pixel 3 XL
Q beta 6
I actually managed (somehow) to get process control to successfully scan one time. Haven't been able to do it again.
That one time was missing things like freeze app, or options other than a complete deletion of the app.
Anyway now, no matter what I try, I seem to be in a constant queued state. Also there seems to be an extra process running (e. g. - starry process control, notification says "2 processes running".)
Going back to Pie after posting this . (And with no TWRP for Q yet that's another pain in the butt)
Logs attached.
[2019-08-10_10.16-sdmaid.zip](https://github.com/d4rken/sdmaid-public/files/3488932/2019-08-10_10.16-sdmaid.zip)

**Comment by d4rken** [comment] 2019-08-10 15:14
Can you record a debug log?
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debug-log

Hanging at "In queue" is usually a root thing are you sure Magisk is running correctly?

**Comment by jancm** [comment] 2019-08-10 21:35
Back on Pie so the debug log is a no go for now (it's a real pain jumping
between the 2 at the moment since the only way to go from Q to Pie is to
totally wipe /data, including /data/media).

I'll be a lot happier once TWRP for Q is available.

I'll keep it in mind when I decide to try again. Maybe sometime next week?
(Big maybe)

Magisk (latest Canary) was definitely working correctly. Titanium, terminal
emulator as root, file explorers, were all processing it correctly (as well
as some scripts and other assorted items).

Also there definitely appeared to be an extra tall running. Try running App
Control notification states that 2 tasks are running. Start
CorpseFinder+SystemCleaner+AppCleaner = 4 tasks running.

The other issue, as I mentioned, was the one time I did get App Control to
work there appeared to be options missing.
Didn't spend a ton of time searching but definitely noticed:
No "freeze app" function
No "Reset" option
No "Delete the app, but keeps the data" option.

**Comment by d4rken** [comment] 2019-08-11 07:32
> Also there definitely appeared to be an extra tall running. Try running App
Control notification states that 2 tasks are running. Start
CorpseFinder+SystemCleaner+AppCleaner = 4 tasks running.

The 4th task is the init task that runs once per new SD Maid session.

> The other issue, as I mentioned, was the one time I did get App Control to
work there appeared to be options missing.
Didn't spend a ton of time searching but definitely noticed:
No "freeze app" function
No "Reset" option
No "Delete the app, but keeps the data" option.

Those all require root.

> Magisk (latest Canary) was definitely working correctly. Titanium, terminal
emulator as root, file explorers, were all processing it correctly (as well
as some scripts and other assorted items).

The issue still points to Magisk, it's not necessarily an Android Q issue though this can happen on any Android version, and can also happen with SuperSU, under some conditions (that I don't understand), the SuperUser app will just not respond when trying to open a root shell. The fix is usually a reboot, removing the hanging app from it's database, or at worst rerooting.

**Comment by jancm** [comment] 2019-08-11 11:27
Ok thanks. I'll try again in a few days and let you know what happens. If I
can't resolve it I'll get you a debug log.

**Comment by jancm** [comment] 2019-08-12 18:42
So it started happening to me on Pie. I think I've tracked down the
trigger. It only seems to happen when I turn off su logging within Magisk.
I have 3 debug logs. All tests were done with AppControl.

mgsklog-on: su logging turned on, SD Maid works correctly.
mgsklog-off: su logging turned off, SD Maid hangs in Queued state.
mgsklog-off.rootcheck-off: su logging turned off, root check also turned
off. SD Maid works correctly.

Need anything else just let me know.

**Comment by jancm** [comment] 2019-08-13 03:25
Looks like replying by email doesn't include attachments. Here's the 3 debug logs I mentioned.
[sdmaid_logfile_1565633967448.txt.mgsklog-on.zip](https://github.com/d4rken/sdmaid-public/files/3495183/sdmaid_logfile_1565633967448.txt.mgsklog-on.zip)
[sdmaid_logfile_1565634191091.mgsklog-off.txt.zip](https://github.com/d4rken/sdmaid-public/files/3495185/sdmaid_logfile_1565634191091.mgsklog-off.txt.zip)
[sdmaid_logfile_1565634376451.mgsklog-off.rootcheck-off.txt.zip](https://github.com/d4rken/sdmaid-public/files/3495187/sdmaid_logfile_1565634376451.mgsklog-off.rootcheck-off.txt.zip)

**Comment by d4rken** [comment] 2019-08-13 07:36
> sdmaid_logfile_1565633967448.txt.mgsklog-on.zip

```
1565633978217  D/RXS:Root:Root: We got ROOT on first try :D !
1565633978217  D/RXS:Root:RootContext: Root: Root(state=ROOTED)
```
Finishes with AppControl being loaded.

> sdmaid_logfile_1565634191091.mgsklog-off.txt.zip

```
1565634201298  D/RXS:Root:Root: We got ROOT on first try :D !
1565634201298  D/RXS:Root:RootContext: Root: Root(state=ROOTED)
(...)
1565634201350  D/RXS:RxShell:Session: writeLine(line=/data/user/0/eu.thedarken.sdm/files/toybox_sdm touch --help, flush=false)
1565634201351  D/RXS:RxShell:Session: writeLine(line=echo a72cf8bc-1afa-465e-9913-0a3c39330185 $?, flush=false)
1565634201351  D/RXS:RxShell:Session: writeLine(line=echo a72cf8bc-1afa-465e-9913-0a3c39330185 >&2, flush=true)
```

Hangs on testing `touch` applet availability.

> sdmaid_logfile_1565634376451.mgsklog-off.rootcheck-off.txt.zip

```
1565634385040  I/RootManager: Initialising RootContext
1565634385040  W/RootManager: Rootcheck is disabled!
1565634385041  I/RootManager: RootContext: RootContext(rootState=Root(state=UNAVAILABLE)
``` 

Finishes with AppControl being loaded.

**Comment by d4rken** [comment] 2019-08-13 07:46
I've not seen this behavior before :thinking: 

Each applet get's checked once against a normal non-root shell and against a root-shell, it hangs on running `/data/user/0/eu.thedarken.sdm/files/toybox_sdm touch --help` in a root shell. 

So the initial root check by just opening a shell via "su" works, we open a shell, check status:
```
1565634201291  V/RXS:Harvester:Output: uid=0(root) gid=0(root) groups=0(root) context=u:r:magisk:s0
```
Get this ^ and assume root.

Then applet tests start, the `touch` one is the first. SD Maid tests it successfully without root and then doesn't get any output when testing it with root.

**Comment by jancm** [comment] 2019-08-13 22:39
It's the latest Canary version.
v19.4-736729f5(19307)

Yes, the current stable (19.3) does work correctly. I've also got the
previous Canary available
v19.4-05658caf(19305)

That one also works correctly. So it's something topjohn introduced in this
latest update.

You can probably explain the problem better than I can but it should
definitely be reported.

**Comment by d4rken** [comment] 2019-08-14 08:59
As this is not an issue in SD Maid, I'm closing this here. I've created a ticket with Magisk: https://github.com/topjohnwu/Magisk/issues/1776

Please add any further details there.

**Closed by d4rken** 2019-08-14 08:59 UTC
Labels: 0 needs info/repro, 3rd party, bug, question

**Comment by d4rken** [comment] 2019-08-14 09:06
@jancm Please confirm the working and non working builds again within the issue ticket on the Magisk repo, are there even closer versions where one works and the other one doesn't? Or have there not been any other versions. This will make it a lot easier to narrow down the cause.
