### ISSUE TITLE
Fix overlapping text in statistics chart

### ISSUE THREAD

**Issue by Novaaaaaaaa** [d4rken/sdmaid-public#3038] opened 2019-10-16 07:59 UTC
Can you please make the percentages not overlap in the statistics page?![](https://i.imgur.com/9EWu5Dh.jpg)

**Comment by d4rken** [comment] 2019-10-16 09:25
I'm using this library:
https://github.com/PhilJay/MPAndroidChart

SD Maid currently uses `3.0.0` and there are newer versions available, I'll update and see if it fixes this.

**Comment by d4rken** [comment] 2019-10-25 13:11
I've updated the lib but the issue is still present.
Fixing this is currently out of scope, the amount of time needed to fix this vs the rewards seems unproportionate at the moment. :frowning:

Rainy day fix...

**Closed** 2019-10-28 11:24 UTC
Labels: OutOfScope, bug, c: Statistics
