### ISSUE TITLE
QuickAcess Bug

### ISSUE THREAD

**Issue by Geocfu** [d4rken/sdmaid-public#303] opened 2016-02-08 22:28 UTC
These bugs are from the Beta version 4.0.5.
I have enabled the "Scan and clean in a single pass" option.

QuickAcess:
**Bug 1:** After the press of the green *"Clean"* button, next to the deleted items on each tab a red button shows up displaying *"DELETE"* instead of displaying *"DELETED"*. As a result if you press the *"DELETE"* button the operation at the tab that you pressed will run again. At the end of the procedure all the tabs that i have enabled(all exept Duplicates) will be displaying a red "*DELETE*" / "*OPTIMIZE*" button impling that the files were not deleted even thought they were. Also  the *"Clean"* button is still replaced with the red "Bin" instead of the green *"Circle"*. (Not sure if it is a bug or not.)

**Bug 2:** After you press the *"Clean"* button and the operation will finish, no matter if you clear the app from the recent apps drawer or by pressing the back button twice, when you will come back, the *"Clean"* button will still be replaced with the red "Bin" instead of the green *"Circle"* and the tabs will be displaying a red "*DELETE*" / "*OPTIMIZE*" button but without the previous cleaned stats.

**EDIT :** 
This bug is from the Beta version 4.0.6.
**Bug 3:** After you press the *"Clean"* button and the operation starts if you receive a call during that time(before the whole procedure finishes) the app will start all over again no matter if it has finished with some tabs or not.

It feels like the app does not update it self after each exit or a complete kill.

**Comment by d4rken** [comment] 2016-02-09 12:43
Regarding Bug 1:
I'm not sure I understand. If you have "Single pass" activated, there shouldn't be any green "clean" button (by clean button you mean the floating action button in the bottom right)?
Because it's a single pass, it always does SCAN followed by DELETE/OPTIMIZE. So after an operation finishes, it will display DELETE again on the button ans this is what happens if you press it each time.
Does this make sense or am I missunderstanding something?

Bug 2:
I can't reproduce this. After triggering all operations, if i swipe SD Maid away or double press to exit, all operations are aborted. If you then enter SD Maid again, it's a fresh start.
I noticed though that if using double press to exit, the notifications might stay behind.

Bug 3:
"Start all over again", do you mean that you open it and it starts automatically, or do you mean that the app opens as a fresh start without previously triggered operations?
I think this is something we can't fix, most likely SD Maid is consuming too much resources for the systems liking and due to the phone call being of the highest priority, SD Maid is killed by the system.

**Comment by Geocfu** [comment] 2016-02-09 13:20
Regarding Bug 1: It makes more sense for me if after the single pass *SCAN* a DELETED label is shown instead of the DELETE button.

Bug 2: I didn't ment to say what you understood. What i wanted to say is that after the *SCAN* and *DELETE* / *OPTIMIZE* has finished, a red floating action button(*BIN*) in the bottom right is being displayed. If i exit the app and then come back again there is no fresh restart. Its like i never exited the app namely the red floating action button(*BIN*) in the bottom right is still there. In my opinion it should be displayed a green floating action button(*CIRCLE*) in the bottom right implying that you have to do it for the first time(since you oppend the app).

Bug 3: "Start all over again", i mean that when you will come back from the phone call at the app, all the operations will start automatically again (without any user's action) regardless which operation has been corrupted from the phone call and stopped instead of continuing the process from there.

**Comment by d4rken** [comment] 2016-02-09 14:02
> Regarding Bug 1: It makes more sense for me if after the single pass SCAN a DELETED label is shown instead of the DELETE button.

So this would be more of an enhancement to the buttons than a bug?
The buttons are buttons though and are not intented to reflect anything but the action they trigger. And even after cleaning the action they trigger is still "DELETE" (in singlepass mode), showing "DELETED" on them doesn't make sense as "DELETED" is not an action but a state.

> What i wanted to say is that after the SCAN and DELETE / OPTIMIZE has finished, a red floating action button(BIN) in the bottom right is being displayed. 

QuickAccess without Single Pass has 3 States: NEW, CAN_DELETE and CANCEL. With SinglePass we only have NEW and CANCEL, due to being single pass, the state CAN_DELETE is always true , because any operations is scan+delete. Thus we have to show the red garbage can button, because it's the action that will be triggered.

> Bug 3: "Start all over again", i mean that when you will come back from the phone call at the app, all the operations will start automatically again (without any user's action) regardless which operation has been corrupted from the phone call and stopped instead of continuing the process from there.

I'd say they are still running. How do you know they have not been running during the phone call? What do you mean by "corrupted" operation?

**Comment by Geocfu** [comment] 2016-02-09 14:27
> Thus we have to show the red garbage can button, because it's the action that will be triggered.

At least make an option to remember preference because now we have to see the  confirmation dialog every time we run the QuickAccess.
> I'd say they are still running. How do you know they have not been running during the phone call?

Because the notifications when i am on the phone call are running for every single tool. Plus when i come back to the app the QuickAccess process is trigged by it self from the start. Also i am not sure if they stop or just no matter what they start from the begining.
> "corrupted"

Syntax error. I wanted to say disrupted.

**Comment by d4rken** [comment] 2016-02-09 14:40
> At least make an option to remember preference because now we have to see the confirmation dialog every time we run the QuickAccess.

Remember what? The confirmation is there to prevent accidental execution. Do you mean to NOT show the confirmation? I could see merit in removing the confirmation completely as people explicitly opted in to use single pass mode, so "quick" is they main desire.

> Because the notifications when i am on the phone call are running for every single tool.

If the notifications are running for every tool it specifically means that the phone call did not interrupt operations! If any of SD Maids worker is active and you put SD Maids UI in the background, a notification will be shown for every active worker. If you open SD Maid again, the notifications will be removed as you can see progress in the main UI.

> Plus when i come back to the app the QuickAccess process is trigged by it self from the start. Also i am not sure if they stop or just no matter what they start from the begining.

Nothing started or stopped, if the UI is reopened, the UI reconnects with the service and if the service has active workers their progress is shown. In this case the workers that are running from before the phone call. SD Maids service is not interrupted by closing the UI.

**Comment by Geocfu** [comment] 2016-02-09 14:48
> I could see merit in removing the confirmation completely as people explicitly opted in to use single pass mode, so "quick" is they main desire.

Thats what i mean.

> Nothing started or stopped

For me after i came back from the call all the processes started from the begining, not from the current last one before the call.

**Comment by d4rken** [comment] 2016-02-09 15:59
>>    I could see merit in removing the confirmation completely as people explicitly opted in to use single pass mode, so "quick" is they main desire.

> Thats what i mean.

Sounds good. Can you make an extra ticket for this enhancement? I'll likely track add it with the next update. Need to finish the current changeset, then it should be an easy addition.

> For me after i came back from the call all the processes started from the begining, not from the current last one before the call.

I currently can't reproduce this and can neither imagine how this could happen.
I'm currently thinking that you just believe it restartet, but in fact just continued. This is especially confusing if you are using SinglePass mode, because for each tool two tasks are submitted (scan+delete). So if you reenter the app you could possibly see one of the tools switch to it's second task, seeming like it started from the beginning (which is somewhat did, just with a different task).

If you are still certain that the action are restarting, record it on a debug run (advanced settings) and reopen the ticket.
Thanks for your valuable feedback!

**Closed by d4rken** 2016-02-09 15:59 UTC
Labels: QuickAccess
