### ISSUE TITLE
Bug: Wrong file size

### ISSUE THREAD

**Issue by JavkhlanK** [d4rken/sdmaid-public#2313] opened 2019-02-17 20:51 UTC
### What happened?
I just copied a apk file from /data/app/com.newnote and pasted it to /sdcard/. Then the apk got pasted and the file size was wrong.

### What did you expect to happen?
I hope, that the bug gets fixed (if it's one) and that the file size is correct.

### How can I reproduce the issue?
1. Just copy a apk file (or something else, i don't know if that works) from /data/app/packagenameofapp and copy it to /sdcard/ (or somewhere else, i didn't try that out). If successful, there will be a size of "0B(actualFileSize)"

### Comments
Hi!

### SD Maid
Version: `4.13.1 (41301)`
Unlocker: `4.2.2 (40202) (true)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `samsung/a5xeltexx/a5xelte:7.0/NRD90M/A510FXXS7CSA1:user/release-keys`

**Comment by JavkhlanK** [comment] 2019-02-17 20:52
I had root access, but then it got corrupted and I leaved it until today

**Comment by d4rken** [comment] 2019-02-18 10:31
I can't reproduce it on my device. Can you record a debug log of this?

**Comment by JavkhlanK** [comment] 2019-02-18 14:28
How?

**Comment by d4rken** [comment] 2019-02-18 14:35
For v4.13.1 you have to fllow these instructions:
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug/8d935428bd801084c7c721043fbc7c937b60fb32#debugrun-log

Or you wait a few days until I release v4.13.2 where I will have simplified this process a lot:
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log

**Comment by JavkhlanK** [comment] 2019-02-18 14:49
=== BEGIN ===
SD Maid logfile: /storage/emulated/0/Android/data/eu.thedarken.sdm/cache/logfiles/sdmaid_logfile_1550501073876.log
1550501073879 I/Debug: Now logging to file!
1550501073880 I/Debug: Debuglevel: 2
1550501073882 I/RXS:Debug: setDebug(debug=true)
1550501073883 D/Debug: Install id: 963bdff9-82bd-4f39-9539-758e68be5e96
1550501073884 I/Debug: F: VERSIONNAME:4.13.1; VERSIONCODE:41301
1550501073885 I/Debug: P: VERSIONNAME:4.2.2; VERSIONCODE:40202
1550501073896 V/RXS:RxCmdShell: isAlive()
1550501073897 V/RXS:RxCmdShell: open()
1550501073900 D/Debug: ro.build.id=NRD90M
1550501073900 D/Debug: ro.build.display.id=NRD90M.A510FXXS7CSA1
1550501073901 D/Debug: ro.build.version.incremental=A510FXXS7CSA1
1550501073901 D/Debug: ro.build.version.sdk=24
1550501073901 D/Debug: ro.build.version.preview_sdk=0
1550501073902 D/Debug: ro.build.version.codename=REL
1550501073902 D/Debug: ro.build.version.all_codenames=REL
1550501073902 D/Debug: ro.build.version.release=7.0
1550501073903 D/Debug: ro.build.version.security_patch=2019-01-01
1550501073903 D/Debug: ro.build.version.base_os=samsung/a5xeltexx/a5xelte:7.0/NRD90M/A510FXXU7CRK1:user/release-keys
1550501073903 D/Debug: ro.build.version.security_index=1
1550501073904 D/Debug: ro.build.date=Fri Jan  4 18:05:25 KST 2019
1550501073904 D/Debug: ro.build.date.utc=1546592725
1550501073905 D/Debug: ro.build.type=user
1550501073905 D/Debug: ro.build.user=dpi
1550501073906 V/RXS:RxShell: open()
1550501073906 D/Debug: ro.build.host=21HHAG09
1550501073906 V/RXS:RxProcess: open()
1550501073906 D/Debug: ro.build.tags=release-keys
1550501073907 D/Debug: ro.build.flavor=a5xeltexx-user
1550501073908 D/Debug: ro.product.model=SM-A510F
1550501073909 D/Debug: ro.product.brand=samsung
1550501073909 D/Debug: ro.product.name=a5xeltexx
1550501073910 D/Debug: ro.product.device=a5xelte
1550501073910 D/Debug: ro.product.board=universal7580
1550501073911 D/Debug: ro.product.cpu.abi=armeabi-v7a
1550501073911 D/Debug: ro.product.cpu.abi2=armeabi
1550501073912 D/Debug: ro.product.cpu.abilist=armeabi-v7a,armeabi
1550501073912 D/Debug: ro.product.cpu.abilist32=armeabi-v7a,armeabi
1550501073912 D/Debug: ro.product.cpu.abilist64=
1550501073913 D/Debug: ro.product.manufacturer=samsung
1550501073913 D/Debug: ro.product.locale=en-GB
1550501073914 D/Debug: ro.build.product=a5xelte
1550501073914 D/Debug: ro.build.description=a5xeltexx-user 7.0 NRD90M A510FXXS7CSA1 release-keys
1550501073915 D/Debug: ro.build.fingerprint=samsung/a5xeltexx/a5xelte:7.0/NRD90M/A510FXXS7CSA1:user/release-keys
1550501073915 D/Debug: ro.build.characteristics=phone,emulator
1550501073916 D/Debug: ro.build.PDA=A510FXXS7CSA1
1550501073916 D/Debug: ro.build.official.release=true
1550501073916 D/Debug: ro.build.changelist=12236002
1550501073917 D/Debug: ro.product_ship=true
1550501073917 D/Debug: ro.product.first_api_level=22
1550501073918 D/Debug: ro.build.scafe.version=2017A
1550501073919 D/Debug: ro.build.selinux=1
1550501073919 V/RXS:RxProcess: processCreator:onNext(Process[pid=8092, hasExited=false])
1550501073920 D/Debug: ro.build.version.sem=2402
1550501073921 D/Debug: ro.build.version.sep=80000
1550501073925 D/RXS:RxProcess: open():doOnSuccess RxProcess.Session(process=Process[pid=8092, hasExited=false])
1550501073925 I/SDMaid: Bugsnag setup done!
1550501073925 V/RXS:RxProcess:Session: input()
1550501073926 V/RXS:RxProcess:Session: output()
1550501073928 D/SDMServiceControl: baseBind() called.
1550501073928 D/SDMServiceControl: Base-binding...
1550501073930 D/SDMaid: Update history: [41012, 41013, 41104, 41105, 41106, 41107, 41108, 41109, 41110, 41200, 41201, 41202, 41203, 41300, 41301]
1550501073931 V/RXS:RxProcess:Session: error()
1550501073931 V/RXS:RxShell:Session: errorLines()
1550501073932 V/RXS:RxProcess:Session: destroy()
1550501073932 V/RXS:RxProcess:Session: waitFor()
1550501073932 V/RXS:RxShell:Session: waitFor()
1550501073933 V/RXS:RxShell: open():doOnSuccess RxShell.Session(processSession=RxProcess.Session(process=Process[pid=8092, hasExited=false]))
1550501073934 V/RXS:RxShell:Session: waitFor()
1550501073942 D/RXS:RxProcess:Session: Waiting for Process[pid=8092, hasExited=false] to exit.
1550501073942 V/RXS:CmdProcessor: attach(RxShell.Session(processSession=RxProcess.Session(process=Process[pid=8092, hasExited=false])))
1550501073944 V/RXS:RxShell:Session: waitFor()
1550501073972 V/RXS:RxShell:Session: waitFor()
1550501073973 V/RXS:RxShell:Session: cancel()
1550501073974 V/RXS:RxCmdShell: open():doOnSuccess eu.darken.a.a.f$b@50bd7f6
1550501073974 V/RXS:RxCmdShell:Session: waitFor()
1550501073975 D/RXS:CmdProcessor: Submitted: Cmd(timeout=0, commands=[printenv])
1550501073979 D/RXS:CmdProcessor: Processing: Cmd(timeout=0, commands=[printenv])
1550501073979 V/RXS:RxShell:Session: outputLines()
1550501073980 V/RXS:Harvester:Output: request(9223372036854775807)
1550501073981 V/RXS:RxShell:Session: errorLines()
1550501073982 V/RXS:Harvester:Error: request(9223372036854775807)
1550501073982 D/RXS:RxShell:Session: writeLine(line=printenv, flush=false)
1550501073983 D/RXS:RxShell:Session: writeLine(line=echo 455bbda2-fa50-4121-ae6d-2d982176f68a $?, flush=false)
1550501073983 D/RXS:RxShell:Session: writeLine(line=echo 455bbda2-fa50-4121-ae6d-2d982176f68a >&2, flush=true)
1550501073991 V/SDMActivity:SDMMainActivity(1c17f7): onNewIntent(savedInstanceState=null)
1550501073992 I/LanguageEnforcer: Enforcing language: de
1550501074020 D/EventDatabase: EventDatabase
1550501074047 V/Fragment:NavigationFragment(84610f5): onAttach(context=eu.thedarken.sdm.main.ui.SDMMainActivity@1c17f7)
1550501074047 V/Fragment:NavigationFragment(84610f5): onCreate(savedInstanceState=null)
1550501074066 V/RXS:Harvester:Output: _=/system/bin/printenv
1550501074066 V/RXS:Harvester:Output: ANDROID_DATA=/data
1550501074066 V/RXS:Harvester:Output: ENC_EMULATED_STORAGE_TARGET=/storage/enc_emulated
1550501074066 V/RXS:Harvester:Output: ANDROID_SOCKET_zygote=8
1550501074067 V/RXS:Harvester:Output: ANDROID_ROOT=/system
1550501074067 V/RXS:Harvester:Output: ANDROID_BOOTLOGO=1
1550501074067 V/RXS:Harvester:Output: ANDROID_ASSETS=/system/app
1550501074067 V/RXS:Harvester:Error: 455bbda2-fa50-4121-ae6d-2d982176f68a
1550501074067 V/RXS:Harvester:Output: BOOTCLASSPATH=/system/framework/core-oj.jar:/system/framework/core-libart.jar:/system/framework/conscrypt.jar:/system/framework/okhttp.jar:/system/framework/core-junit.jar:/system/framework/bouncycastle.jar:/system/framework/ext.jar:/system/framework/framework.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/ims-common.jar:/system/framework/apache-xml.jar:/system/framework/org.apache.http.legacy.boot.jar:/system/framework/sprengine.jar:/system/framework/knoxsdk.jar:/system/framework/sec_edm.jar:/system/framework/sagearpolicymanager.jar:/system/framework/smartbondingservice.jar:/system/framework/timakeystore.jar:/system/framework/fipstimakeystore.jar:/system/framework/knoxvpnuidtag.jar:/system/framework/sec_sdp_sdk.jar:/system/framework/sec_sdp_hidden_sdk.jar:/system/framework/esecomm.jar:/system/framework/SemAudioThumbnail.jar:/system/framework/smatlib.jar:/system/framework/samsung-framework.jar
1550501074067 V/RXS:Harvester:Output: ASEC_MOUNTPOINT=/mnt/asec
1550501074067 D/RXS:Harvester:Error: endHarvest(isComplete=true, isDone=false)
1550501074068 V/RXS:Harvester:Output: MC_AUTH_TOKEN_PATH=/efs
1550501074068 V/RXS:Harvester:Output: EXTERNAL_STORAGE=/sdcard
1550501074068 V/RXS:Harvester:Output: ANDROID_STORAGE=/storage
1550501074068 V/RXS:CmdProcessor: errorLines():doOnEach: OnNextNotification[eu.darken.a.a.d$b@94426c4]
1550501074068 V/RXS:Harvester:Output: KNOX_STORAGE=/data/knox/ext_sdcard
1550501074068 V/RXS:Harvester:Output: PATH=/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin
1550501074068 V/RXS:CmdProcessor: errorLines():doOnEach: OnCompleteNotification
1550501074068 V/RXS:Harvester:Output: SYSTEMSERVERCLASSPATH=/system/framework/services.jar:/system/framework/ethernet-service.jar:/system/framework/wifi-service.jar:/system/framework/samsung-services.jar:/system/framework/ssrm.jar:/system/framework/hqm.jar
1550501074069 V/RXS:Harvester:Output: 455bbda2-fa50-4121-ae6d-2d982176f68a 0
1550501074069 D/RXS:Harvester:Output: endHarvest(isComplete=true, isDone=false)
1550501074069 V/RXS:CmdProcessor: outputLine():doOnEach: OnNextNotification[eu.darken.a.a.e$a@56c69ad]
1550501074069 V/RXS:CmdProcessor: outputLine():doOnEach: OnCompleteNotification
1550501074070 D/RXS:CmdProcessor: Post zip: OnNextNotification[QueueCmd(command=Cmd(timeout=0, commands=[printenv]), exitCode=0, output.size()=15, errors.size()=0)]
1550501074070 V/RXS:CmdProcessor: onNext(QueueCmd(command=Cmd(timeout=0, commands=[printenv]), exitCode=0, output.size()=15, errors.size()=0))
1550501074071 I/RXS:CmdProcessor: Processed: Cmd.Result(cmd=Cmd(timeout=0, commands=[printenv]), exitcode=0, output.size()=15, errors.size()=0)
1550501074071 V/RXS:RxCmdShell:Session: close()
1550501074071 V/RXS:CmdProcessor: isIdle: OnNextNotification[false]
1550501074071 V/RXS:CmdProcessor: isIdle: OnNextNotification[true]
1550501074072 V/RXS:RxShell:Session: close()
1550501074072 D/RXS:RxShell:Session: writeLine(line=exit, flush=true)
1550501074073 V/RXS:RxShell: LineStream:error onComplete()
1550501074073 V/RXS:RxShell: LineStream:output onComplete()
1550501074074 V/RXS:RxShell: LineStream:error onCancel()
1550501074074 D/RXS:RxProcess:Session: Exitcode: 0, Process: Process[pid=8092 ,hasExited=true, exitcode=0]
1550501074074 V/RXS:RxProcess: processCreator:onComplete()
1550501074075 V/RXS:RxProcess: cancel()
1550501074075 V/RXS:RxProcess:Session: waitFor():doOnSuccess 0
1550501074075 D/RXS:UserKiller: kill(Process[pid=8092 ,hasExited=true, exitcode=0])
1550501074075 V/RXS:RxShell:Session: waitFor():doOnSuccess 0
1550501074075 V/RXS:CmdProcessor: Attached session ended!
1550501074075 D/RXS:UserKiller: Process is no longer alive, skipping kill.
1550501074076 V/RXS:CmdProcessor: Poison pill!
1550501074076 V/RXS:RxShell:Session: close():doOnSuccess 0
1550501074076 V/RXS:RxProcess: Process finished, clearing session
1550501074076 D/RXS:CmdProcessor: Post zip: OnCompleteNotification
1550501074076 V/RXS:RxCmdShell:Session: close():doOnSuccess 0
1550501074076 V/RXS:RxShell: LineStream:output onCancel()
1550501074076 V/RXS:CmdProcessor: onComplete()
1550501074076 D/Debug: Environment variables:
1550501074076 D/Debug: _=/system/bin/printenv
1550501074076 D/Debug: ANDROID_DATA=/data
1550501074077 D/Debug: ENC_EMULATED_STORAGE_TARGET=/storage/enc_emulated
1550501074077 D/Debug: ANDROID_SOCKET_zygote=8
1550501074077 D/Debug: ANDROID_ROOT=/system
1550501074077 D/Debug: ANDROID_BOOTLOGO=1
1550501074077 D/Debug: ANDROID_ASSETS=/system/app
1550501074077 D/Debug: BOOTCLASSPATH=/system/framework/core-oj.jar:/system/framework/core-libart.jar:/system/framework/conscrypt.jar:/system/framework/okhttp.jar:/system/framework/core-junit.jar:/system/framework/bouncycastle.jar:/system/framework/ext.jar:/system/framework/framework.jar:/system/framework/telephony-common.jar:/system/framework/voip-common.jar:/system/framework/ims-common.jar:/system/framework/apache-xml.jar:/system/framework/org.apache.http.legacy.boot.jar:/system/framework/sprengine.jar:/system/framework/knoxsdk.jar:/system/framework/sec_edm.jar:/system/framework/sagearpolicymanager.jar:/system/framework/smartbondingservice.jar:/system/framework/timakeystore.jar:/system/framework/fipstimakeystore.jar:/system/framework/knoxvpnuidtag.jar:/system/framework/sec_sdp_sdk.jar:/system/framework/sec_sdp_hidden_sdk.jar:/system/framework/esecomm.jar:/system/framework/SemAudioThumbnail.jar:/system/framework/smatlib.jar:/system/framework/samsung-framework.jar
1550501074077 D/Debug: ASEC_MOUNTPOINT=/mnt/asec
1550501074078 D/Debug: MC_AUTH_TOKEN_PATH=/efs
1550501074078 D/Debug: EXTERNAL_STORAGE=/sdcard
1550501074078 D/Debug: ANDROID_STORAGE=/storage
1550501074078 D/Debug: KNOX_STORAGE=/data/knox/ext_sdcard
1550501074078 D/Debug: PATH=/sbin:/vendor/bin:/system/sbin:/system/bin:/system/xbin
1550501074078 D/Debug: SYSTEMSERVERCLASSPATH=/system/framework/services.jar:/system/framework/ethernet-service.jar:/system/framework/wifi-service.jar:/system/framework/samsung-services.jar:/system/framework/ssrm.jar:/system/framework/hqm.jar
1550501074084 V/Fragment:NavigationFragment(84610f5): onViewCreated(view=android.widget.LinearLayout{f2eac7 V.E...... ......I. 0,0-0,0}, savedInstanceState=null)
1550501074084 I/SDMMainActivity: Ready in a moment!
1550501074088 V/SDMMainActivity: initDrawer
1550501074091 I/SchedulerWard: Checking scheduler...
1550501074091 I/Startup: 430ms
1550501074092 I/SchedulerManager: Scheduler enabled: true
1550501074093 D/SDMServiceControl: Bind request, now managing 1 customers (customers=[eu.thedarken.sdm.main.ui.SDMMainActivity@1c17f7]).
1550501074093 I/SchedulerWard: Schedule should exist and does exist. Yay!
1550501074093 D/SDMServiceControl: binder()
1550501074093 V/SDMActivity:SDMMainActivity(1c17f7): onStart()
1550501074094 V/Fragment:NavigationFragment(84610f5): onActivityCreated(savedInstanceState=null)
1550501074096 V/Fragment:ExplorerFragment(a594a92): onAttach(context=eu.thedarken.sdm.main.ui.SDMMainActivity@1c17f7)
1550501074096 V/Fragment:ExplorerFragment(a594a92): onCreate(savedInstanceState=null)
1550501074160 D/UIPostHelper: attach(android.support.design.widget.CoordinatorLayout{514333f V.E...... ......I. 0,0-0,0 #7f090096 app:id/coordinatorlayout})
1550501074161 V/Fragment:ExplorerFragment(a594a92): onViewCreated(view=android.support.design.widget.CoordinatorLayout{514333f V.E...... ......I. 0,0-0,0 #7f090096 app:id/coordinatorlayout}, savedInstanceState=null)
1550501074161 V/Fragment:ExplorerFragment(a594a92): onActivityCreated(savedInstanceState=null)
1550501074164 V/SDMActivity:SDMMainActivity(1c17f7): onResume()
1550501074166 V/Fragment:NavigationFragment(84610f5): onResume()
1550501074166 D/SDMServiceControl: binder()
1550501074167 V/Fragment:ExplorerFragment(a594a92): onResume()
1550501074167 D/PiwikHelper: TrackTime UNLOCKER in 2
1550501074167 D/SDMServiceControl: binder()
1550501074179 D/PIWIK:Tracker: Event added to the queue: org.piwik.sdk.d@9b1a76a
1550501074211 D/SDMService: onCreate()
1550501074214 D/PiwikHelper: TrackTime SDMAID in 1
1550501074217 D/SDMService: onBind(intent=Intent { cmp=eu.thedarken.sdm/.main.core.SDMService launchParam=MultiScreenLaunchParams { mDisplayId=0 mBaseDisplayId=0 mFlags=0 } })
1550501074222 D/UIPostHelper: onViewAttachedToWindow(android.support.design.widget.CoordinatorLayout{514333f V.E...... ......I. 0,0-0,0 #7f090096 app:id/coordinatorlayout})
1550501074451 V/QuickAccessWidgetProvider: ExternalEventSet onReceive(Intent { act=eu.thedarken.sdm.ACTION_EXTERNAL_EVENT flg=0x10 cmp=eu.thedarken.sdm/.oneclick.widget.QuickAccessWidgetProvider launchParam=MultiScreenLaunchParams { mDisplayId=0 mBaseDisplayId=0 mFlags=0 } bqHint=1 (has extras) })
1550501074453 D/SDMServiceControl: onServiceConnected(name=ComponentInfo{eu.thedarken.sdm/eu.thedarken.sdm.main.core.SDMService}, binder=eu.thedarken.sdm.main.core.SDMService$a@391db0e)
1550501074454 D/SDMServiceHelper: setBackgroundMode(previous=true, now=false)
1550501074468 D/Exclusions:Repo: Data version: 6, Desired version: 6
1550501074469 D/Exclusions:Repo: Loading result for: data.user -> [{"contains_string":"/storage/emulated/0/games/","tags":["DUPLICATES"],"timestamp":1525631217495,"type":"SIMPLE_CONTAINS"},{"contains_string":"com.besome.sketch","tags":["DATABASES","APPCONTROL","DUPLICATES","CORPSEFINDER","SYSTEMCLEANER","APPCLEANER"],"timestamp":1534097103238,"type":"SIMPLE_CONTAINS"},{"contains_string":"/storage/emulated/0/.sketchware","tags":["DATABASES","APPCONTROL","DUPLICATES","CORPSEFINDER","APPCLEANER","SYSTEMCLEANER"],"timestamp":1534097162164,"type":"SIMPLE_CONTAINS"},{"contains_string":"/storage/2DD2-4731/","tags":["DUPLICATES","SYSTEMCLEANER","APPCLEANER","CORPSEFINDER"],"timestamp":1534339373956,"type":"SIMPLE_CONTAINS"},{"contains_string":"/storage/emulated/0/.cloudagent","tags":["DUPLICATES"],"timestamp":1540903425335,"type":"SIMPLE_CONTAINS"},{"contains_string":"/storage/emulated/0/AppProjects/","tags":["DUPLICATES"],"timestamp":1549177702810,"type":"SIMPLE_CONTAINS"},{"contains_string":"/storage/emulated/0/.aide","tags":["DUPLICATES"],"timestamp":1550171708880,"type":"SIMPLE_CONTAINS"}]
1550501074475 D/c: WorkerStatus: WorkerStatus(isWorking=false, primary='null', secondary='null', progress=[0/0], isCancelable=true, progressType=NONE)
1550501074479 D/f: WorkerStatus: WorkerStatus(isWorking=false, primary='null', secondary='null', progress=[0/0], isCancelable=true, progressType=NONE)
1550501074482 D/e: WorkerStatus: WorkerStatus(isWorking=false, primary='null', secondary='null', progress=[0/0], isCancelable=true, progressType=NONE)
1550501074507 D/b: WorkerStatus: WorkerStatus(isWorking=false, primary='null', secondary='null', progress=[0/0], isCancelable=true, progressType=NONE)
1550501074510 D/c: WorkerStatus: WorkerStatus(isWorking=false, primary='null', secondary='null', progress=[0/0], isCancelable=true, progressType=NONE)
1550501074513 D/c: WorkerStatus: WorkerStatus(isWorking=false, primary='null', secondary='null', progress=[0/0], isCancelable=true, progressType=NONE)
1550501074517 D/CorpseFinder:Settings: CorpseFinder uninstall watcher state: Desired true, current true
1550501074518 D/d: WorkerStatus: WorkerStatus(isWorking=false, primary='null', secondary='null', progress=[0/0], isCancelable=true, progressType=NONE)
1550501074523 D/b: WorkerStatus: WorkerStatus(isWorking=false, primary='null', secondary='null', progress=[0/0], isCancelable=true, progressType=NONE)
1550501074649 D/ExplorerFragment: internalSwitchWorkingState(WorkerStatus(isWorking=false, primary='null', secondary='null', progress=[0/0], isCancelable=true, progressType=NONE))
1550501074651 D/GlideGif: setState(fragment=ExplorerFragment{a594a92 #1 id=0x7f090093 eu.thedarken.sdm.explorer.ui.ExplorerFragment}, state=INTRO
1550501077036 V/Fragment:DebugFragment(ee48c7): onAttach(context=eu.thedarken.sdm.main.ui.SDMMainActivity@1c17f7)
1550501077037 V/Fragment:DebugFragment(ee48c7): onCreate(savedInstanceState=null)
1550501077037 V/Fragment:ExplorerFragment(a594a92): onPause()
1550501077039 V/Fragment:ExplorerFragment(a594a92): onDestroyView()
1550501077059 V/Fragment:ExplorerFragment(a594a92): onDestroy()
1550501077060 V/Fragment:ExplorerFragment(a594a92): onDetach()
1550501077138 V/Fragment:DebugFragment(ee48c7): onViewCreated(view=android.widget.ScrollView{dca3e21 VFED.V... ......I. 0,0-0,0}, savedInstanceState=null)
1550501077147 V/Fragment:DebugFragment(ee48c7): onActivityCreated(savedInstanceState=null)
1550501077148 V/Fragment:DebugFragment(ee48c7): onResume()
1550501077152 D/PIWIK:Tracker: Event added to the queue: org.piwik.sdk.d@8116c07
1550501077462 V/SDMMainActivity: onDrawerClosed
1550501084784 V/SDMActivity:SDMMainActivity(1c17f7): onPause()
1550501084786 V/Fragment:NavigationFragment(84610f5): onPause()
1550501084787 V/Fragment:DebugFragment(ee48c7): onPause()
1550501084855 D/SDMServiceControl: Unbind request, now managing 0 customers (customers=[]).
1550501084855 D/SDMServiceControl: binder()
1550501084856 D/SDMServiceHelper: setBackgroundMode(previous=false, now=true)
1550501084857 V/SDMActivity:SDMMainActivity(1c17f7): onStop()
1550501084859 D/SDMaid: onTrimMemory: TRIM_MEMORY_UI_HIDDEN
1550501084864 D/PIWIK:EventDiskCache: Cache check took 1ms
1550501084865 D/PIWIK:EventDiskCache: Uncaching of 0 events took 0ms
1550501084865 D/PIWIK:EventCache: Switched state to ONLINE, uncached 0 events from disk.
1550501084865 D/PIWIK:Dispatcher: Drained 2 events.
1550501085393 D/PIWIK:DefaultPacketSender: status code 200
1550501085395 D/PIWIK:Dispatcher: Dispatched 2 events.
1550501085398 D/PIWIK:EventDiskCache: Cache check took 0ms
1550501095058 V/SDMActivity:SDMMainActivity(1c17f7): onRestart()
1550501095059 D/SDMServiceControl: Bind request, now managing 1 customers (customers=[eu.thedarken.sdm.main.ui.SDMMainActivity@1c17f7]).
1550501095060 D/SDMServiceControl: binder()
1550501095061 D/SDMServiceHelper: setBackgroundMode(previous=true, now=false)
1550501095064 V/SDMActivity:SDMMainActivity(1c17f7): onStart()
1550501095065 V/SDMActivity:SDMMainActivity(1c17f7): onResume()
1550501095069 V/Fragment:NavigationFragment(84610f5): onResume()
1550501095069 D/SDMServiceControl: binder()
1550501095070 D/PiwikHelper: TrackTime UNLOCKER in 3
1550501095082 V/Fragment:DebugFragment(ee48c7): onResume()
1550501095088 D/PIWIK:Tracker: Event added to the queue: org.piwik.sdk.d@ba8eaea
1550501096540 V/SDMMainActivity: onDrawerOpened
1550501097295 V/SDMRecyclerView: onRecyclerItemClick(pos:4)->true
1550501097297 V/Fragment:ExplorerFragment(ec6b5fa): onAttach(context=eu.thedarken.sdm.main.ui.SDMMainActivity@1c17f7)
1550501097297 V/Fragment:ExplorerFragment(ec6b5fa): onCreate(savedInstanceState=null)
1550501097298 V/Fragment:DebugFragment(ee48c7): onPause()
1550501097298 V/Fragment:DebugFragment(ee48c7): onDestroyView()
1550501097384 D/UIPostHelper: attach(android.support.design.widget.CoordinatorLayout{cdaf9be V.E...... ......I. 0,0-0,0 #7f090096 app:id/coordinatorlayout})
1550501097385 V/Fragment:ExplorerFragment(ec6b5fa): onViewCreated(view=android.support.design.widget.CoordinatorLayout{cdaf9be V.E...... ......I. 0,0-0,0 #7f090096 app:id/coordinatorlayout}, savedInstanceState=null)
1550501097385 V/Fragment:ExplorerFragment(ec6b5fa): onActivityCreated(savedInstanceState=null)
1550501097386 V/Fragment:ExplorerFragment(ec6b5fa): onResume()
1550501097386 D/SDMServiceControl: binder()
1550501097389 D/PIWIK:Tracker: Event added to the queue: org.piwik.sdk.d@c85e204
1550501097482 D/ExplorerFragment: internalSwitchWorkingState(WorkerStatus(isWorking=false, primary='null', secondary='null', progress=[0/0], isCancelable=true, progressType=NONE))
1550501097484 D/GlideGif: setState(fragment=ExplorerFragment{ec6b5fa #3 id=0x7f090093 eu.thedarken.sdm.explorer.ui.ExplorerFragment}, state=INTRO
1550501097737 V/SDMMainActivity: onDrawerClosed
1550501099913 D/WorkerHub: Task submitted: CDTask(targetPath=/storage/emulated/0, targetFile=null)
1550501099914 D/WorkerHub: Creating TaskProcessor for: e
1550501099915 D/WorkerHub:Processor:e: Task submitted: CDTask(targetPath=/storage/emulated/0, targetFile=null)
1550501099915 D/e: WorkerStatus: WorkerStatus(isWorking=true, primary='In Warteschlange', secondary='null', progress=[0/0], isCancelable=true, progressType=NONE)
1550501099920 D/SDMService: Acquiring wakelock while processing tasks.
1550501099922 D/ThreadOverlord: allowedWorkers: 8
1550501099923 V/ThreadOverlord: Active/Queued tasks: 2 | Active threads: 1 | Queued threads: 1 | Completed threads: 0
1550501099923 I/BaseConditions: Setting up base conditions.
1550501100052 D/ExplorerFragment: internalSwitchWorkingState(WorkerStatus(isWorking=true, primary='In Warteschlange', secondary='null', progress=[0/0], isCancelable=true, progressType=NONE))
1550501100053 D/GlideGif: setState(fragment=ExplorerFragment{ec6b5fa #3 id=0x7f090093 eu.thedarken.sdm.explorer.ui.ExplorerFragment}, state=WORKING
1550501100072 V/QuickAccessWidgetProvider: ExternalEventSet onReceive(Intent { act=eu.thedarken.sdm.ACTION_EXTERNAL_EVENT flg=0x10 cmp=eu.thedarken.sdm/.oneclick.widget.QuickAccessWidgetProvider launchParam=MultiScreenLaunchParams { mDisplayId=0 mBaseDisplayId=0 mFlags=0 } bqHint=1 (has extras) })
1550501100127 I/RootManager: Initialising RootContext
1550501100135 D/RXS:Root:RootContext: Building RootContext...
1550501100136 V/RXS:RxCmdShell: open()
1550501100136 V/RXS:RxShell: open()
1550501100136 V/RXS:RxProcess: open()
1550501100155 V/RXS:RxProcess: processCreator:onNext(Process[pid=8202, hasExited=false])
1550501100156 D/RXS:RxProcess: open():doOnSuccess RxProcess.Session(process=Process[pid=8202, hasExited=false])
1550501100156 V/RXS:RxProcess:Session: input()
1550501100157 V/RXS:RxProcess:Session: output()
1550501100157 V/RXS:RxProcess:Session: error()
1550501100157 V/RXS:RxShell:Session: errorLines()
1550501100158 V/RXS:RxProcess:Session: destroy()
1550501100159 V/RXS:RxProcess:Session: waitFor()
1550501100159 V/RXS:RxShell:Session: waitFor()
1550501100159 V/RXS:RxShell: open():doOnSuccess RxShell.Session(processSession=RxProcess.Session(process=Process[pid=8202, hasExited=false]))
1550501100160 V/RXS:RxShell:Session: waitFor()
1550501100160 D/RXS:RxProcess:Session: Waiting for Process[pid=8202, hasExited=false] to exit.
1550501100161 V/RXS:CmdProcessor: attach(RxShell.Session(processSession=RxProcess.Session(process=Process[pid=8202, hasExited=false])))
1550501100171 V/RXS:RxShell:Session: waitFor()
1550501100172 V/RXS:RxShell:Session: waitFor()
1550501100172 V/RXS:RxShell:Session: cancel()
1550501100173 V/RXS:RxCmdShell: open():doOnSuccess eu.darken.a.a.f$b@c042702
1550501100175 V/RXS:RxCmdShell:Session: waitFor()
1550501100181 D/RXS:Root:RootContext: SeLinux: SELinux(state=ENFORCING)
1550501100185 D/RXS:CmdProcessor: Submitt




I sent you an email with a recording of the bug

**Comment by d4rken** [comment] 2019-02-18 14:59
The log is incomplete and it will be too large to post here anyways. I need to be attached/zipped.

I watched the video you emailed.

Does the copied file work? If you upload it or move it to a computer does it work?

It shows two sizes `0 B (3.5 MB)` which is weird, see here for an explanation of the value:
https://github.com/d4rken/sdmaid-public/wiki/explorer#file-size

**Comment by JavkhlanK** [comment] 2019-02-18 15:18
The file works, and after an reload, the correct size gets shown.
Here is the full log:
[sdmaid_logfile_1550502838193.log](https://github.com/d4rken/sdmaid-public/files/2876259/sdmaid_logfile_1550502838193.log)

**Comment by d4rken** [comment] 2019-02-18 18:16
Good log :+1: 

SD Maid uses `stat` to get the output from the filesystem:

```
660:regular file:28:2416 :0:9997:3660694:512:0:1550502866:`/storage/emulated/0/base.apk'
``` 

At the end we see `512:0`. `512` is the block size in byte, and 0 is the amount of blocks used, with `512*0=0` the size in blocks is 0. The actual size of `3660694` is correct, and later on a subsequent call the blocksize is count is displayed correctly, with `512:7160`, i.e. 512B*7160=3665920 Byte.

Currently I'd say the bug is within the filesystem/kernel of your device, the filesystem information is not being updated fast enough? Or only indirectly.

What happens if you copy/paste it to external storage, e.g. sdcard, which will have a different filesystem?

**Comment by JavkhlanK** [comment] 2019-02-18 19:36
Oh. If I copy it to my SD-Card, there is 3.5 MB. 👌

**Comment by d4rken** [comment] 2019-02-18 20:10
I'm closing this as this is not a bug in SD Maid, and not something I'm willing to add a ROM specific workaround for.

Independent of that, this was a very good issue ticket and don't hesitate to report things like this again.
I'm to have documented this behavior.

**Closed by d4rken** 2019-02-18 20:10 UTC
Labels: 0 needs info/repro, 3rd party, bug, c: Explorer
