### ISSUE TITLE
app control crashes after hitting the refresh button

### ISSUE THREAD

**Issue by patrickdrd** [d4rken/sdmaid-public#2284] opened 2019-02-01 19:23 UTC
I've clicked send twice, can you check?

**Comment by d4rken** [comment] 2019-02-01 21:21
On the Google Play Crash dialog? I won't be able to match that to you :frowning: 

Can you tell me your install ID? I'll check SD Maids own crash tracker.

**Comment by d4rken** [comment] 2019-02-01 21:39
Long press the settings button in SD Maid to get the install ID.

I'll try to find  the report later but GPlay crash tracking is really shitty and has no good filters...

What's the SD Maid/Android Version and device type?

**Comment by patrickdrd** [comment] 2019-02-01 21:53
install id: 01dc565e-e6f4-4f05-8b2a-cb9f0df48679
Android 7.1
sd maid 4.12.3

**Comment by d4rken** [comment] 2019-02-01 21:58
Device model?

**Comment by patrickdrd** [comment] 2019-02-01 22:12
Nokia 6

**Comment by d4rken** [comment] 2019-02-04 09:15
I couldn't find it. You'll have to record it by hand, e.g. with ADB or catlog if you have root.

**Comment by patrickdrd** [comment] 2019-02-04 09:19
I don't have root on that phone so please give instructions for adb

**Comment by patrickdrd** [comment] 2019-02-05 08:41
well, it worked yesterday, as it used to be working before the "problem period",
that's why I didn't post log, I'll post next time it happens

**Comment by d4rken** [comment] 2019-04-28 12:36
Closing due to not enough info to fix/reproduce.

**Closed by d4rken** 2019-04-28 12:36 UTC
Labels: 0 needs info/repro, c: AppControl
