### ISSUE TITLE
Canceling Bug

### ISSUE THREAD

**Issue by Geocfu** [d4rken/sdmaid-public#302] opened 2016-02-08 21:38 UTC
These bugs are from the Beta version 4.0.5.
I run the SystemCleaner from the left-to-right slide menu. Then i stopped the opperation from the X button. The operation started to cancel it self but the canceling operation is being kept for ever. It also triggers a notification that is also being kept for ever. The operation from within the app and the notification respectively will stop only when i clear the app from the recent apps drawer.
This also applies for all the operations.

**Comment by d4rken** [comment] 2016-02-09 12:29
I'm confused. Does this happen for all tools and operations or just SystemCleaner operations?
Are you running with root?

**Comment by Geocfu** [comment] 2016-02-09 12:42
I am running with supersu 2.45 on cyanogenmod 12.1.
I think it happens also on the QuickAccess for the running tabs that got the command to cancel their operations.

**Comment by d4rken** [comment] 2016-02-09 12:45
QuickAccess is just a collection of shortcuts, if the service switches states i.e. goes "Canceling" it has "reached" the backend. I could reproduce it for the SystemCleaner and it seems to be regression due to changes i made to the shell system. Likely fixed in the next update. Thanks!

**Comment by Geocfu** [comment] 2016-02-09 13:34
Keep in mind that this might be for all the tools. Thank you for taking care of my opinion and for your efforts.

**Closed** 2016-02-10 01:09 UTC
Labels: beta, bug, Tool/SystemCleaner
