### ISSUE TITLE
Toggeling receivers has no effect

### ISSUE THREAD

**Issue by antonioroz** [d4rken/sdmaid-public#314] opened 2016-03-02 02:18 UTC
It happens that pressing disable the startup application, the button does not work, it stays the same.
![screenshot_2016-03-01-20-04-56](https://cloud.githubusercontent.com/assets/17583028/13448714/bed3e04e-dfea-11e5-8066-e9058285007e.png)
![screenshot_2016-03-01-20-05-10](https://cloud.githubusercontent.com/assets/17583028/13448717/c447045c-dfea-11e5-8a7a-b7df245e4965.png)

**Comment by d4rken** [comment] 2016-03-02 04:28
Can you do a debug run (advanced settings), reproduce the issue and attach the logfile to this ticket?
It will be in sdcard/Android/data/eu.thedarken.sdm/filse/logfiles/

**Comment by d4rken** [comment] 2016-03-08 08:06
Reopen if you can provide a debug run log, I currently can't reproduce this behavior.

**Closed** 2016-03-09 14:31 UTC
Labels: beta, more info, Tool/AppControl
