### ISSUE TITLE
Oppo A9 (2020)

### ISSUE THREAD

**Issue by Hunterus2020** [d4rken/sdmaid-public#3639] opened 2020-07-02 13:18 UTC
When searching, the garbage weight in applications is one (several GB, and after directly cleaning it is completely different (200 MB with a little)?  And the search itself is fast, almost instant, and the removal takes 1.5 hours (I'm not joking)!  123 applications ...  For the first time I came across this, on other devices was not.

Applications-Scan-Delete

Oppo A9 (2020) on ColorOS 6.0.1  based on Android 9

**Comment by d4rken** [comment] 2020-07-04 17:39
Can you show a screenshot or a video of what takes 1.5hours?

This sounds like the https://github.com/d4rken/sdmaid-public/wiki/AppCleaner is running with the accessbility option and  that option isn't working and it just takes 1.5 hours to fail through every app.

If I'm right, please provide a debug log of a few apps failing:
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log

**Comment by Hunterus2020** [comment] 2020-07-04 21:42
Hello!  It looks like this:

https://drive.google.com/file/d/12yfScz6h5Jhv8VM35cgSH3vFlaKBOvEL/view?usp=drivesdk

сб, 4 июл. 2020 г., 20:39 Matthias Urhahn <notifications@github.com>:

**Comment by vatonbero** [comment] 2020-07-06 10:59
Hi there,

Happens my LOS 17.1 on starlte (Galaxy S9) as well. SDMaid has permissions for accessibility but it never cleans 100%, it is just spinning this. I have used this SDMaid version on OneUI 2.1 (Android 10, Samsung stock) 4 days ago and it worked like a charm there.

80 apps here and SD maid completed after 30+ minutes. I have reproduced this with much less apps this time.

Log is here:
[sdmaid_logfile_1594032281061.txt.zip](https://github.com/d4rken/sdmaid-public/files/4878422/sdmaid_logfile_1594032281061.txt.zip)

**Comment by Hunterus2020** [comment] 2020-07-06 11:41
Hi!
Will you be this problem?  Is it solvable?

пн, 6 июл. 2020 г., 13:59 vatonbero <notifications@github.com>:

**Comment by Hunterus2020** [comment] 2020-07-06 11:43
Can you fix it?

сб, 4 июл. 2020 г., 20:39 Matthias Urhahn <notifications@github.com>:

**Comment by vatonbero** [comment] 2020-07-06 13:02
> Can you fix it? сб, 4 июл. 2020 г., 20:39 Matthias Urhahn <notifications@github.com>:

Eh, no. We will wait for Darken to check this and validate are the issues the same.

**Comment by d4rken** [comment] 2020-07-06 17:42
@Hunterus2020  I need a debug log from you like the one from @vatonbero , see: https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log
You don't need to wait for the whole scan. When SD Maid has skipped the first app, you can stop the recording.

The feature works by knowing what to press on the screen, in both of your cases, SD Maid doesn't recognize anything, but because it's two completely different ROMs, it's to separate issues.

@vatonbero Let's continue your issue here: #3652

**Comment by Hunterus2020** [comment] 2020-07-07 01:18
Hi!
I attach the log-file:
https://drive.google.com/file/d/13tm-Z02rVABuvA-kXwzyleNr8zNlx49B/view?usp=drivesdk

пн, 6 июл. 2020 г., 20:42 Matthias Urhahn <notifications@github.com>:

**Comment by d4rken** [comment] 2020-07-07 12:05
Thanks. ColorOS has changed a lot with Android 9. This will need more work.

Is it possible to change the language to English, and show me in a video what has to be pressed to clear the cache?

**Comment by Hunterus2020** [comment] 2020-07-08 01:37
Hi (again)!
Here's a video in english:
https://drive.google.com/file/d/140DVRt-wrGmRsw7_6mxQYyMyvvaaq2wD/view?usp=drivesdk

вт, 7 июл. 2020 г., 15:05 Matthias Urhahn <notifications@github.com>:

**Comment by d4rken** [comment] 2020-07-08 09:17
The texts in the video are still in english?
I think you might have changed only SD Maids language? SD Maids language can stay the same, I need the system language to be in english.

I need a video + a log in english so I can figure out what SD Maid has to press :smile:.

**Comment by Hunterus2020** [comment] 2020-07-25 05:38
Hello!
I update OS on my device to ColorOS v.7.1 (based on Android 10)
The problem is still relevant :)
video:
https://drive.google.com/file/d/166J8mniK0qiddBnJXDWNsdhaWpV2DtJR/view?usp=drivesdk

ср, 8 июл. 2020 г., 12:17 Matthias Urhahn <notifications@github.com>:

**Comment by Hunterus2020** [comment] 2020-07-25 05:52
+ logfile:
https://drive.google.com/file/d/16NIvPWNnP2POeCtF8UxbkAyWh4SxDn24/view?usp=drivesdk

пн, 6 июл. 2020 г., 20:42 Matthias Urhahn <notifications@github.com>:

**Comment by d4rken** [comment] 2020-07-29 05:04
Thanks, should be fixed in the update :+1:

**Closed by d4rken** 2020-07-29 05:04 UTC
Labels: c: AppCleaner, enhancement
