### ISSUE TITLE
Bug: Accessibility Cache cleaning appears ineffective

### ISSUE THREAD

**Issue by DetlevCM** [d4rken/sdmaid-public#2473] opened 2019-04-09 18:56 UTC
### What happened?
Had 300MB of "hidden cache" files yesterday evening, now 550MB but only dropped to 538MB

### What did you expect to happen?
Hidden cache to reduce to about 300MB, same as yesterday evening

### How can I reproduce the issue?
Use the cache cleaning via accessibility services

### Comments
BlackBerry Key2 

### SD Maid
Version: `4.14.0 (41400)`
Unlocker: `4.3.7 (40307) (true)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `blackberry/bbf100dsglobalindia/bbf100:8.1.0/OPM1.171019.026/ABN088:user/release-keys`

**Comment by d4rken** [comment] 2019-04-10 06:02
After scan SD Maid says there is 550MB to be deleted, but after deletion only says 538MB can be deleted, so just 22MB have been deleted?
Have I understood the issue?

Please record a debug log of it and if possible also a video.

**Comment by DetlevCM** [comment] 2019-04-10 06:12
Yes, pretty much, except that it is 12MB not 22 ;).
I don't think I can get a video of the problem - but I can look into debug logs in the evening if there are instructions on how to obtain them.

In addition I noticed that SD Maid returns an error "Failed to find & click 'Clear cache'" - which seems weird, given I see the Settings Window with the clear cache button...

I tried rebooting and also verified that SD Maid has all permissions - i.e. Storage, Accessibility and Usage Access.
There is no way of uploading a screenshot on Github from Firefox on the phone it seems...

**Comment by d4rken** [comment] 2019-04-10 06:28
> I don't think I can get a video of the problem - but I can look into debug logs in the evening if there are instructions on how to obtain them.

https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debug-log

>In addition I noticed that SD Maid returns an error "Failed to find & click 'Clear cache'" - which seems weird, given I see the Settings Window with the clear cache button...
>I tried rebooting and also verified that SD Maid has all permissions - i.e. Storage, Accessibility and Usage Access.

Ah okay, well then that's the issue :). It's not about permissions, SD Maid just fails to navigate the UI. This may be due to ROM or language differences.

> There is no way of uploading a screenshot on Github from Firefox on the phone it seems...

You have to request the desktop site, it's not optimal :man_shrugging: .

**Comment by DetlevCM** [comment] 2019-04-10 06:37
#response_container_BBPPID{font-family: initial; font-size:initial; color: #1F497D;}  The desktop site didn't give me an upload button either on the phone (weirdly enough) - I tried.So now I'm trying the email response...The language shouldn't be an issue as it is plain English... - And the BlackBerry Android is pretty close to "stock" from what I understand about the look and layout.(I could go into a rant about Android, but that doesn't help with this issue...)                                                                                                                                                                        Sent from my BlackBerry                                                                                                                                                                           From: notifications@github.comSent: 10 April 2019 08:28To: sdmaid-public@noreply.github.comReply to: reply@reply.github.comCc: detlevcm@googlemail.com; author@noreply.github.comSubject: Re: [d4rken/sdmaid-public] Bug: Accessibility Cache cleaning appears ineffective (#2473)  

I don't think I can get a video of the problem - but I can look into debug logs in the evening if there are instructions on how to obtain them.



https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debug-log



In addition I noticed that SD Maid returns an error "Failed to find & click 'Clear cache'" - which seems weird, given I see the Settings Window with the clear cache button...

I tried rebooting and also verified that SD Maid has all permissions - i.e. Storage, Accessibility and Usage Access.



Ah okay, well then that's the issue :). It's not about permissions, SD Maid just fails to navigate the UI. This may be due to ROM or language differences.



There is no way of uploading a screenshot on Github from Firefox on the phone it seems...



You have to request the desktop site, it's not optimal 🤷‍♂️ .

**Comment by d4rken** [comment] 2019-04-10 09:12
How does the page before the "Clear cache" button one look like?

> The desktop site didn't give me an upload button either on the phone (weirdly enough) - I tried.So now I'm trying the email response... (which is a mess...)

That seems to have worked, on the desktop site you can press the bottom of the post window (usually).

The log file only contains SD Maid initializing, not the AppCleaner using the accessibility service. Can you try to record another one? :heart:

**Comment by DetlevCM** [comment] 2019-04-10 10:01
Yes, it is a bit of a struggle and one has to refresh the page, but then the upload works. Strange that it didn't record running the cleaning. I tried again. I hope this log is better.

[sdmaid_logfile_1554890376162.txt.zip](https://github.com/d4rken/sdmaid-public/files/3063169/sdmaid_logfile_1554890376162.txt.zip)

**Comment by d4rken** [comment] 2019-04-10 10:18
That one was spot on :+1: 

So SD Maid correctly found the storage entry, and then doesn't find the "Clear Cache" button.

This is what SD Maid sees, or rather this is the cache button from SD Maids PoV:

```
1554890405904  V/ACC:ACCrawler: Crawling: android.view.accessibility.AccessibilityNodeInfo@1cee0; boundsInParent: Rect(0, 0 - 519, 126); boundsInScreen: Rect(540, 480 - 1059, 606); packageName: com.android.settings; className: android.widget.Button; text: CLEAR CACHE; error: null; maxTextLength: -1; contentDescription: null; viewIdResName: com.android.settings:id/right_button; checkable: false; checked: false; focusable: true; focused: false; selected: false; clickable: true; longClickable: false; contextClickable: false; enabled: true; password: false; scrollable: false; importantForAccessibility: true; actions: [AccessibilityAction: ACTION_FOCUS - null, AccessibilityAction: ACTION_SELECT - null, AccessibilityAction: ACTION_CLEAR_SELECTION - null, AccessibilityAction: ACTION_CLICK - null, AccessibilityAction: ACTION_ACCESSIBILITY_FOCUS - null, AccessibilityAction: ACTION_NEXT_AT_MOVEMENT_GRANULARITY - null, AccessibilityAction: ACTION_PREVIOUS_AT_MOVEMENT_GRANULARITY - null, AccessibilityAction: ACTION_SET_SELECTION - null, AccessibilityAction: ACTION_SHOW_ON_SCREEN - null]
```

I first thought it was because the text label was `CLEAR CACHE` but I already accounted for that. The issue is that I'm filtering for `it.viewIdResourceName?.contains(":id/button")` but the buttons ID is actually  `com.android.settings:id/right_button`.

I didn't know this differs so much (e.g. Blackberry ROM vs AOSP ROM), will be fixed in the next update, if there are still issues then just reopen this ticket or create a new one :+1:.

**Closed** 2019-04-10 14:26 UTC
Labels: bug, c: AppCleaner
