### ISSUE TITLE
Theme issue - EditTextPreference Dialogs not readable

### ISSUE THREAD

**Issue by dukelc** [d4rken/sdmaid-public#421] opened 2016-06-19 23:57 UTC
In 4.2.6 in Bug reporting settings, can not see mail when writing it, and when click ok it adds it but not showing.
![screenshot_20160620-021048](https://cloud.githubusercontent.com/assets/16635770/16180672/b59e2388-368c-11e6-8cb9-9ed3129a79f6.png)
![screenshot_20160620-021101](https://cloud.githubusercontent.com/assets/16635770/16180673/b9f416f4-368c-11e6-915b-ef8d01992d31.png)

**Comment by d4rken** [comment] 2016-06-20 10:20
What ROM and Android version?

**Comment by dukelc** [comment] 2016-06-20 11:33
[This ](http://forum.xda-developers.com/galaxy-s4/i9505-orig-develop/jdcteam-android-source-project-mra58v-t3251663)

**Comment by d4rken** [comment] 2016-06-20 15:25
Caused by changing target API to 24.
Good catch. Will be fixed with next update.

**Closed** 2016-06-23 00:59 UTC
Labels: beta, bug
