### ISSUE TITLE
Changing app language leaves some of the lines in original language

### ISSUE THREAD

**Issue by azumukupoe** [d4rken/sdmaid-public#1619] opened 2018-03-31 16:22 UTC
![SS](https://i.imgur.com/vwavtMD.png)

**Comment by d4rken** [comment] 2018-04-01 06:25
Did you restart SD Maid?

**Comment by azumukupoe** [comment] 2018-04-01 06:28
@d4rken Yes.

**Comment by d4rken** [comment] 2018-04-01 10:31
Which language and SD Maid version?

Are you referring to the tootl names "CorpseFinder" etc.?

**Comment by azumukupoe** [comment] 2018-04-01 10:45
@d4rken No, the results and stuff.

**Comment by d4rken** [comment] 2018-04-01 10:58
I think SD Maid was not restarted completely.

Swipe it from recent tasks or force stop it via system. The UI has been reloaded, but not the service.

**Comment by azumukupoe** [comment] 2018-04-01 11:02
@d4rken Trust me, I've deleted cache and restarted my phone but still shows me this.

**Comment by d4rken** [comment] 2018-04-01 11:51
I can not reproduce this.
I've launched a clean install of SD Maid on a MotoG3 running LineAgeOS 14.1.
The device language is "english", I've set SD Maids "enforce language" setting to german.
The language correctly changes.

The only way I could reproduce is, is when I only restarted the UI by exiting via back button. Then the UI language changed, but the "task results" did not.

You didn't answer my question regarding which languages are used.
Please also provide additional details regarding your device and Android version.

**Comment by azumukupoe** [comment] 2018-04-01 11:56
@d4rken Device language is Japanese and app language is English

**Comment by d4rken** [comment] 2018-04-01 16:24
Why do you ignore half of my questions? 😒 

I don't like to have to drag every bit of detail out of you 😕 . 
I ask a second time: Which device and ROM this is?

I've tried to reproduce it with these specific lanuages, but can't.

* [Initial](https://user-images.githubusercontent.com/1439229/38175198-0cff0f6e-35d9-11e8-9a10-5ac237225e53.png)
* [Incomplete restart via back button](https://user-images.githubusercontent.com/1439229/38175200-17964762-35d9-11e8-91f0-cbf44f944dde.png)
* [Complete restart by force closing SD Maid](https://user-images.githubusercontent.com/1439229/38175218-2eea1e84-35d9-11e8-9afd-3be92ccd57df.png)
* [Settings](https://user-images.githubusercontent.com/1439229/38175223-4a55a67a-35d9-11e8-9e81-711fa74adc6f.png)

Please create a video recording of your reproduction of this issue.

**Comment by azumukupoe** [comment] 2018-04-01 16:50
@d4rken 
I'm sorry for that.
![SD Maid](https://i.imgur.com/0qMwEhJ.png)

I'll try to make a recording.

**Comment by d4rken** [comment] 2018-04-01 16:53
Please also record that you force-closed SD Maid after changing the language setting.

**Comment by d4rken** [comment] 2018-04-26 12:48
@azumukupoe Did you make a video?

**Closed** 2018-05-14 20:32 UTC
Labels: c: General UI&UX, c: QuickAccess, needs info/repro

**Comment by d4rken** [comment] 2018-05-14 22:31
I can't reproduce the issue and you didn't provide the video I asked for, so there is nothing I can do.

**Comment by azumukupoe** [comment] 2018-05-14 22:32
Actually, I don't understand why I has to send you a video because I am just simply using the app.

**Comment by d4rken** [comment] 2018-05-14 22:58
To fix a bug I need to either understand it so I know what to change in the code, or I need to be able to reproduce bug on my device so I can work towards understanding.

I checked the relevant code and can't find an obvious flaw and I can't reproduce it with the description you have given.

So either this is an issue specific to your device, or I'm not reproducing it correctly and a video would help.
