### ISSUE TITLE
Add a Tasker plugin for cleaning when an action happens

### ISSUE THREAD

**Issue by cyandotapps** [d4rken/sdmaid-public#385] opened 2016-05-07 10:50 UTC
There's an app called Tasker, which is able to do actions on a set event, like doing changing screen brightness when the charger is plugged in, or, using modules, making touches on the screen when an SMS is recieved.

My point is, that it would be great if SD Maid had a Tasker plugin where you could choose which cleaning actions (AppCleaner, Databases, etc.) are executed when set as an action via that plugin.

**Comment by d4rken** [comment] 2016-05-07 13:58
Duplicate of #83 
Long time wish, just didn't find the time yet.

If you have some time, feel free to add a description to #83 about how you would use it, when, what options the UI should have. The more details i have the easier it will be to design.

My current idea would be for this to be a sepperate (paid) app that the user can install which would allow Tasker to send tasks to SD Maid.

**Closed by d4rken** 2016-05-07 13:58 UTC

**Comment by gaya4** [comment] 2016-10-22 15:25
Cannot help to develop, but would appreciate a tasker module.
My setup would be something like:
IF charging AND 3:00AM -> cleanup. charging normally charges the mobile fully+more. battery intesive tasks I would then put into this "fully charged and connected to charger timeframe". Titanium Backup is another candidate. Apps, if their name is not Tasker, are normally greenified, if they are started.
So the schedule in SD Maid will not work for me.

Nasty Workaround: Using the shell you can simulate touch input. Tasker can execute shell commands in the background.
Tasker: Execute shell: "input tap x-coordinate y-coordinate", coordinate values in pixel, as per your screen resolution. That works only if the screen is on. But even that.... you could possibly do with tasker...
