### ISSUE TITLE
Bug: App Cache cleaning stopped working (BlackBerry Key2)

### ISSUE THREAD

**Issue by DetlevCM** [d4rken/sdmaid-public#2628] opened 2019-05-29 11:06 UTC
### What happened?
Unsure when and how, but cache cleaning stopped working. - I could revive it once by re-enabling accessibility services, but they seem on right now and it does not work... - will try a reboot next.

### What did you expect to happen?
App cache cleaning should work as expected.

### How can I reproduce the issue?
Unsure - it seemed to have happened after an update...

### SD Maid
Version: `4.14.14 (41414)`
Unlocker: `4.3.8 (40308) (true)`

### Device
Root: `RootContext(rootState=Root(state=UNAVAILABLE)`
Fingerprint: `blackberry/bbf100dsglobalindia/bbf100:8.1.0/OPM1.171019.026/ABT974:user/release-keys`

**Comment by DetlevCM** [comment] 2019-05-29 11:09
This could be equally well an OS level chnage and not an SD Maid problem, who knows with google...

[sdmaid_logfile_1559127565118.txt.zip](https://github.com/d4rken/sdmaid-public/files/3232138/sdmaid_logfile_1559127565118.txt.zip)
[sdmaid_logfile_1559128017009.txt.zip](https://github.com/d4rken/sdmaid-public/files/3232139/sdmaid_logfile_1559128017009.txt.zip)

**Comment by d4rken** [comment] 2019-05-29 11:15
If the ACS service is activated, but not running, and toggeling it does not change that, then the service may have crashed repeatedly and the system has "punished" it for that. To reset that you may have to reboot.

The logs show an okay scan, but if the root cause is that the ACS service crashed, then this will only be visible when it's actually crashing during the log.

Long-press "Settings" in SD Maid and copy paste your install ID into this ticket, I'll see if the automatic crash tracking picked something up.

**Comment by DetlevCM** [comment] 2019-05-29 11:19
I got it running again - turned accessibility off and on.
Another suspect is the disabled automatic launch (BlackBerry Power Management) for SD Maid.

Here is the ID too: 
3737985a-e892-4718-95d0-731c9981a16c

**Comment by d4rken** [comment] 2019-05-29 11:24
No reports for that ID :man_shrugging: 

I don't it's related to power managment, this would only cause isues if you don't have SD Maid opened.

Accumulate some apps with caches so that it runs a bit.
In SD Maids debug menu (where the ID is), there a setting that now reads "Armed: true", set it to false, then SD Maid will not actually delete files. Then repeat the AppCleaner Scan + Delete a few times and see if you can reproduce the issue somehow.

Once you know how it can be reproduced we can try a log again.

While this can certainly be a ROM issue, I would expect it to be all or nothing and not sometimes/sometimes not. :thinking:

**Comment by DetlevCM** [comment] 2019-05-29 12:09
OK, so I just had a quick play: it is indeed the power center.... Disabling the automatic startup stops the accessibility service in SD Maid from working...

Rebooted - it worked.
Disabled automatic startup - it fails

So I'm going to guess it is related to that. - You may want to contact BlackBerry in case the log shows a clear cause as they developped the "Power Center" for the Key2.

The log should contain both events:

[sdmaid_logfile_1559131494236.txt.zip](https://github.com/d4rken/sdmaid-public/files/3232343/sdmaid_logfile_1559131494236.txt.zip)

**Comment by d4rken** [comment] 2019-05-29 12:32
If you go into the AppCleaner settings, does it show a warning icon for the ACS service option?

If you go to delete something via the main AppCleaner page, does it say that the service is enabled but not running?

If you go to Device > Developer Options > Running Processes, does it show the ACSService as running under SD Maid?

**Comment by DetlevCM** [comment] 2019-05-29 12:35
On the Quick Access Screen it just failed.

In the App Cleaner Panel it showed a warning.
I believe that under developer options I had a situation where it was shown as not running while the settings were "on".

**Comment by d4rken** [comment] 2019-05-29 13:20
Is the BlackBerry Power Management a specific app, does it have distinct packagename?

**Comment by DetlevCM** [comment] 2019-05-29 13:25
It is indeed. - com.blackberry.batterycenter

![Screenshot_20190529-152417](https://user-images.githubusercontent.com/1845934/58560683-e93cfd80-8225-11e9-85a3-6f554e6d00b1.png)

**Comment by d4rken** [comment] 2019-05-29 15:00
Hm so far I don't see any solution but display a warning...

**Comment by DetlevCM** [comment] 2019-05-29 15:07
If this remains a BlackBerry only thing, this might be the only sensible solution right now.
Should other manufacturers start offering similar power saving features it might be worth the effort to develop other solutions.

For now, I know that "automatic startup" should remain enabled in the BlackBerry Power Center.

**Comment by d4rken** [comment] 2019-05-29 15:18
Can you add a screenshot of this setting for completeness?

**Comment by DetlevCM** [comment] 2019-05-29 15:29
Screenshots of the Power Center? No problem.

![Screenshot_20190529-171918](https://user-images.githubusercontent.com/1845934/58569918-52793c80-8237-11e9-9e43-997edb94a1cd.png)

![Screenshot_20190529-171930](https://user-images.githubusercontent.com/1845934/58569933-57d68700-8237-11e9-8b12-d1b6ffec8d67.png)

**Comment by d4rken** [comment] 2019-05-29 16:30
I've added an troubleshooting info to the wiki with a link to this ticket:
https://github.com/d4rken/sdmaid-public/wiki/AppCleaner#troubleshooting

I'll close this as I currently see no solution to this from my end.

Thanks for troubleshooting this with me and providing all the details, I'm sure it will save other BlackBerry users some time.

I'll edit the title so maybe it even helps some other devs.

**Closed by d4rken** 2019-05-29 16:30 UTC
Labels: 3rd party, Can't fix, c: AppCleaner, question
