### ISSUE TITLE
App Cleaner - MIUI/Xiaomi Issue with App info/Accessability to clear cache

### ISSUE THREAD

**Issue by SkyDontFall** [d4rken/sdmaid-public#4923] opened 2021-06-10 05:05 UTC
Phone - POCO X3
OS - Android 11 RKQ1.200826.002
MIUI 12 - 12.0.5
App version - 5.1.4
Unlocker version - 4.4.1

Issue - In the app info section, clearing cache automatically doesn't wor
Recording - [Video Recording](https://cdn.discordapp.com/attachments/728207504881745983/852406301162340352/Screenrecorder-2021-06-10-10-06-24-2330.mp4)

Side note - There are two versions of the app info in MIUI (could be something to look into)
Accessed by SD Maid and any third party app trying to access the app info (tried it with Nova Launcher)
![](https://cdn.discordapp.com/attachments/728207504881745983/852412960935510046/Screenshot_2021-06-10-10-16-48-186_com.android.settings.jpg)

Accessed through the settings or recent apps screen 
![](https://cdn.discordapp.com/attachments/728207504881745983/852412961276690463/Screenshot_2021-06-10-10-16-16-184_com.miui.securitycenter.jpg)

**Comment by d4rken** [comment] 2021-06-13 10:39
Can you provide a debuglog?
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log

**Comment by SkyDontFall** [comment] 2021-06-13 13:42
Here you go!


[sdmaid_logfile_1623591512762.txt](https://github.com/d4rken/sdmaid-public/files/6643966/sdmaid_logfile_1623591512762.txt)

**Comment by d4rken** [comment] 2021-06-19 15:37
Thanks, but you need to record the log while reproducing the problem.
The attached log only shows SD Maid being opened, afaict.

**Comment by SkyDontFall** [comment] 2021-06-28 03:31
I'm sorry, I realise that now. I recorded logs again.
Here you go. Hopefully, this helps. 
[sdmaid_logfile_1624850507438.txt.zip](https://cdn.discordapp.com/attachments/728207504881745983/858912196729241610/sdmaid_logfile_1624850507438.txt.zip)

**Comment by SkyDontFall** [comment] 2021-07-19 06:57
Is there anything else I need to provide or is this enough?

**Comment by d4rken** [comment] 2021-08-09 19:09
I checked the log and SD Maid is trying to confirm that the current window is the right one, i.e. for Telegram Plus.
SD Maid is trying to read the "Plus", but according to the log, the system says that the screen data has changed, but does not return any data to SD Maid.

Not sure if this can be fixed on my end :thinking:

**Comment by SkyDontFall** [comment] 2021-08-10 03:35
Well, I messed up.  Didn't mean to close it.

So, I use Bouncer to remove permissions. It works flawlessly. Could they be doing something differently?

**Comment by SkyDontFall** [comment] 2021-08-11 13:22
Hi, I found another app where it actually works (only the app info cleaning) 

1TapCleaner. I tried a lot of other apps and none of them had this feature.. Can you see what they are doing differently?

**Comment by d4rken** [comment] 2021-09-26 08:51
Looks like it also needs quite some time to get the screen info, but at least it can continue.
I'll check if I can add some kind of refresh/requery mechanism on retry.

**Comment by SkyDontFall** [comment] 2021-09-28 16:17
> I have similar issue here, but seems SkyDontFall didn't enclose what happened to the UI.... Or I missed it.
> 
> Previously, the app work as intended. However, since I **disabled MIUI optimization** from developer menu, the accessibility layer of SD Maid didn't work properly (as I guessed the layout different).


You're right, I did disabled MIUI optimization.

**Closed** 2021-10-06 13:02 UTC
Labels: enhancement, c: AppCleaner, 0 needs info/repro
