### ISSUE TITLE
App control cannot work properly

### ISSUE THREAD

**Issue by LC-BX** [d4rken/sdmaid-public#458] opened 2016-08-07 05:39 UTC
Hi, after I took the admin's advice and installed the 4.2.13 version of SD Maid, things are just perfect, thanks to whoever that admin is.
Now I've noticed a small problem with SD Maid.
If I've mannually changed the permission of a folder, say root/system/app/123(made it read-only), then the app control of SD Maid can't work fully. For example, it cannot delete ANY system app now.
And after I restore the rights of the folder I mentioned before, SD Maid can work fully again.
PS: I have three same phone with same rom and same root and same SD maid(I mean I've done cross checks), so I'm pretty sure that we can leave other variables out of this situation.
Thanks for your attention~

**Comment by d4rken** [comment] 2016-08-07 11:00
Hi, thanks for your report!

> whoever that admin is.

What admin?

> If I've mannually changed the permission of a folder, say root/system/app/123(made it read-only), then the app control of SD Maid can't work fully.

Do you mean `/system/app/....`? Those folders are already read-only by default, because the `/system` partition is read-only by default on all Android devices.
What perrmissions exactly, did you set?

> For example, it cannot delete ANY system app now.

Hm it certainly should have no effect on ALL other system apps.

A log file should tell us what's going on, please record one: 
https://github.com/d4rken/sdmaid-public/wiki/Reporting-a-bug#debugrun-log

Preferably, try to reproduce it on the log, meaning: Change permissions, then delete something such that it fails.

**Comment by LC-BX** [comment] 2016-08-08 00:02
ehmm,by admin I mean whoever anwsered me lasr time, I'm not sure your ID is used by one person. Ah that's not important~
OK I understand the debug log thing and I'll do it asap. More info:
1.the permission, I've managed it with RE, and I've changed it to r--r--r-, read-only for everyone.No write and no execute. The SD Maid failed to change the permission on this one.
2.The SD maid didn't show it failed.It showed that the deleting process was successful.
3.Should I paste the content of the log here? Or should I upload it somewhere? Sorry^_^

**Comment by LC-BX** [comment] 2016-08-08 00:08
Oh and by ANY system app, I mean those that can originally be deleted by SD maid(on my other phone)

**Comment by LC-BX** [comment] 2016-08-08 00:16
Ok...The log file is 22MB(pretty sure it was only created moments ago)...What should I do now...

**Comment by d4rken** [comment] 2016-08-08 12:16
> ehmm,by admin I mean whoever anwsered me last time, I'm not sure your ID is used by one person. 

That was probably also me then, this is a one-man show :wink: 

> 1.the permission, I've managed it with RE, and I've changed it to r--r--r-, read-only for everyone.No write and no execute. The SD Maid failed to change the permission on this one.

What's "RE"? Note that in some cases you need +x on directories in order to traverse them.

> Unfortunately, we don’t support that file type. 

I noticed that too, GitHub bug? You can always mail stuff to support@darken.eu and then just reference this ticket.

> So I upload it to an online drive:
> https://www.jianguoyun.com/p/DXow9LQQucaDBhjanBk
> The download button is on top right...Thx

I doesn't let me download it without creating an account. You could change the `.log` to `.txt` and upload it to GitHub (if it allows such big attachments) or zip it and mail it.

**Comment by LC-BX** [comment] 2016-08-09 02:26
Hi pal,
I've send you the log file via Email with the title #458. 
by RE I mean Root Explorer, a powerful file-manager, very commonly used in my country, by Speed Software Ltd.
"you need +x on directories in order to traverse them."---Sorry,I didn't understand that~


And here are the things that I've done during the log:
---start SD Maid
---try to change the permission of a folder under the path system\app, and failed
---changed the perm. of that folder with RE
---start App control, try to delete a system app(wich can be deleted by SD Maid before), it says successful
---start App control again and scan and the app is still there
---force-close that app and reset it and then delete it (I did the test couple of days ago and the detail may be a little wrong, but what I mean is, I tried many ways to delete the app with SD maid and failed.)
---reset the perm. with RE
---delete the app with SD Maid and succeed.

Thx for all your help~:-)

**Comment by tuffss** [comment] 2016-08-10 21:36
Hey thanks.. going to root my galaxy sm,s820l. It will b my first.. any
suggestions. Thanks

**Comment by LC-BX** [comment] 2016-08-11 01:04
@tuffss 
Ehmm... sorry? who are U talking to again?

**Comment by LC-BX** [comment] 2016-08-11 01:05
@d4rken Hi pal, I've send you the log, pls acknowledge？

**Comment by d4rken** [comment] 2016-08-11 05:10
Got it :+1: , just didn't have time yet to look through the log yet.

**Comment by d4rken** [comment] 2016-08-28 00:43
Huge backlog, sorry it took me so long to get around to it.

So changing the permission in SD Maid didn't actually fail.
The remounting code is a bit crude (will be improved in the nextupdate) and threw and errorcode and that masked the successful error code of the `chmod` command.

Changing the permission:

```
1470614731874 V/SDM:InteractiveShell: outStream|toybox mount -o rw,remount '/system'
1470614731874 V/SDM:InteractiveShell: outStream|$BUSYBOX mount -o rw,remount '/system' '/system'
1470614731874 V/SDM:InteractiveShell: outStream|$BUSYBOX chmod  u+r-w-x,g+r-w-x,o+r-w-x '/system/app/XiaomiVip'
1470614731874 V/SDM:InteractiveShell: outStream|$BUSYBOX mount -o ro,remount '/system' '/system'
1470614731875 V/SDM:InteractiveShell: outStream|toybox mount -o ro,remount '/system'
1470614732053 V/SDM:StreamHarvester: Error:Segmentation fault 
1470614732219 V/SDM:StreamHarvester: Output:f41e919f-ca1d-4bb3-8cb9-833061da8057 139
1470614732219 V/SDM:StreamHarvester: Error:Segmentation fault 
```

Seg faults are from the `toybox mount`.
Next scan shows the permissions are changed (**444** is read-read-read):
```
1470614732350 V/SDM:StreamHarvester: Output:444:directory:45848:510:0:0:4096:512:8:1470614732:/system/app/XiaomiVip
```

First uninstall is this:

```
1470614810276 D/SDM:Uninstaller: Uninstalling com.xiaomi.gamecenter[keepData:false]
```

Uninstall removes the app, but it's either a user app or an **updated system app**.
The uninstall completes succesfully.

Same for the second app `com.xiaomi.pass`.

The permission changing was unrelated as far as I can see, it was just an issue of interpreting the exitcodes correctly anyways.

Currently uninstalling updated system apps requires 2 uninstalls, the first one removes the updated version of the app, the second uninstall removes the original version from `/system` some devices require a restart inbetween in order for this to be done cleanly. Looking to improve on this, but it's not trivial and still on the TODO list.

Permission issue should be fixed with the next update (v4.3.0) if you still experience problems with it, please make a new ticket just for the permission changing in the Explorer.

If the system app uninstalling was not caused by what I described please reopen the ticket and provide some more info. (Note that v4.3.0 will improve upon that too, but uninstall updated system apps will still require 2 uninstalls).

**Closed by d4rken** 2016-08-28 00:43 UTC
Labels: c: AppControl, more info

**Comment by LC-BX** [comment] 2016-08-29 15:59
Hi, sorry to reopen this issue again, but there's a serious misunderstanding here.
I've changed the permisson of that folder with SD maid and this action indeed failed. I've checked that with other trustworthy tool(RE). 
You said after re-scan the permission was changed, that's because I've changed it manually with RE and this of course was not logged.
So about the permission thing, I'm sorry but I've written the steps and I wrote clearly "---changed the perm. of that folder with RE"
If you need the APK of RE I'm happy to provide... I'm curios what app are u guys using as advanced-Explorer anyway...
And the uninstall thing, maybe you're right, I've came aross that situation recently after I flash a new rom, and I  did not change any permission before uninstalling. It did take a reboot and twice action. 
I decide to wait for the 4.3 and try the original situation once again.
All in all, I just want to inform u that the permission change do have failed.

THX for all your concern and for reading the whole log file! 
LC

**Comment by d4rken** [comment] 2016-08-29 16:33
> You said after re-scan the permission was changed, that's because I've changed it manually with RE and this of course was not logged.

Ok I missunderstood that then. If this issue still exists after the next update please make a new ticket just for the Explorer permission issue.

> If you need the APK of RE I'm happy to provide... I'm curios what app are u guys using as Advanced-Explorer anyway...

What guys? Just me here. I use SD Maids explorer or a console.
