### ISSUE TITLE
Backup and Restore of Settings

### ISSUE THREAD

**Issue by deblood3** [d4rken/sdmaid-public#5368] opened 2022-02-26 14:31 UTC
**Additional context**

I am asking if backup and Restore settings feature can be added to the app in any future update/upgrade.

This will help to restore existing settings when you switch to a new phone or after a hardware reset of phone. 

Thanks
Alfred.

**Comment by d4rken** [comment] 2022-03-02 16:37
Duplicate of #599

**Closed by d4rken** 2022-03-02 16:37 UTC
Labels: enhancement
